// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUe0yiXXkhhWQYHNGspKSzpo3NK3g5PqM',
    appId: '1:359874826415:web:dcee2377319b14b21d445a',
    messagingSenderId: '359874826415',
    projectId: 'javierub-appflutter',
    authDomain: 'javierub-appflutter.firebaseapp.com',
    storageBucket: 'javierub-appflutter.appspot.com',
    measurementId: 'G-7D27FX3883',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCdZojjdYdmZG44Chu9LahYm7ON9sORq4',
    appId: '1:359874826415:android:e96e01d12200e6081d445a',
    messagingSenderId: '359874826415',
    projectId: 'javierub-appflutter',
    storageBucket: 'javierub-appflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_W74kWa7LS3cyrZBEG7fmQEPXBV_xgQ',
    appId: '1:359874826415:ios:511a705e20f222831d445a',
    messagingSenderId: '359874826415',
    projectId: 'javierub-appflutter',
    storageBucket: 'javierub-appflutter.appspot.com',
    iosBundleId: 'com.javierub.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX_W74kWa7LS3cyrZBEG7fmQEPXBV_xgQ',
    appId: '1:359874826415:ios:511a705e20f222831d445a',
    messagingSenderId: '359874826415',
    projectId: 'javierub-appflutter',
    storageBucket: 'javierub-appflutter.appspot.com',
    iosBundleId: 'com.javierub.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUe0yiXXkhhWQYHNGspKSzpo3NK3g5PqM',
    appId: '1:359874826415:web:60770c1ba129bc171d445a',
    messagingSenderId: '359874826415',
    projectId: 'javierub-appflutter',
    authDomain: 'javierub-appflutter.firebaseapp.com',
    storageBucket: 'javierub-appflutter.appspot.com',
    measurementId: 'G-0HVG95GDPL',
  );
}
